name: Unit Tests (Vitest Coverage)

on:
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.1.0'

      - name: Install dependencies
        run: npm ci

      - name: Run Vitest coverage
        run: npm run test:coverage
